[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@1inch/=../1inch_contracts/limit-order-protocol-master/",
    "@chainlink/=lib/chainlink/"
]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"